In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/tomek/Desktop/CME_metadata.csv', parse_dates=['from_date', 'to_date'])

In [3]:
df.head()

,code,name,description,refreshed_at,from_date,to_date
0,0DF2015,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-12-28
1,0DF2016,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-02-02
2,0DF2017,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2017-02-03 01:05:31,2014-11-21,2017-02-02
3,0DF2018,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-02-03 01:07:36,2014-11-21,2018-02-02
4,0DF2019,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-11-01 22:11:08,2015-02-12,2018-11-01

In [4]:
df.rename(columns={'code': 'symbol'}, inplace=True)

In [5]:
df.head()

,symbol,name,description,refreshed_at,from_date,to_date
0,0DF2015,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-12-28
1,0DF2016,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-02-02
2,0DF2017,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2017-02-03 01:05:31,2014-11-21,2017-02-02
3,0DF2018,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-02-03 01:07:36,2014-11-21,2018-02-02
4,0DF2019,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-11-01 22:11:08,2015-02-12,2018-11-01

In [6]:
data = pd.read_csv('C:/Users/tomek/zipline/bundles/expiration_dates.csv',
                   usecols=['expiration_date', 'symbol'],
                   index_col=['symbol'],
                  parse_dates=['expiration_date'])

In [7]:
data.head()

        expiration_date
symbol
0DF2019      2019-01-31
0DF2020      2020-01-31
0DG2019      2019-02-28
0DG2020      2020-02-28
0DH2019      2019-03-29

In [8]:
end_dates = pd.DataFrame(df['to_date'])

In [9]:
end_dates.index = df['symbol']

In [10]:
end_dates.head()

           to_date
symbol
0DF2015 2016-12-28
0DF2016 2016-02-02
0DF2017 2017-02-02
0DF2018 2018-02-02
0DF2019 2018-11-01

In [11]:
end_dates.rename(columns={'to_date': 'expiration_date'}, inplace=True)

In [12]:
end_dates.head()

        expiration_date
symbol
0DF2015      2016-12-28
0DF2016      2016-02-02
0DF2017      2017-02-02
0DF2018      2018-02-02
0DF2019      2018-11-01

In [13]:
expiration_dates = data.combine_first(end_dates)

In [14]:
expiration_dates.head()

        expiration_date
symbol
0DF2015      2016-12-28
0DF2016      2016-02-02
0DF2017      2017-02-02
0DF2018      2018-02-02
0DF2019      2019-01-31

In [15]:
df['expiration_date'] = df.symbol.map(expiration_dates.expiration_date)

In [16]:
df.head()

,symbol,name,description,refreshed_at,from_date,to_date,expiration_date
0,0DF2015,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-12-28,2016-12-28
1,0DF2016,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-06-29 17:33:32,2014-02-18,2016-02-02,2016-02-02
2,0DF2017,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2017-02-03 01:05:31,2014-11-21,2017-02-02,2017-02-02
3,0DF2018,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-02-03 01:07:36,2014-11-21,2018-02-02,2018-02-02
4,0DF2019,Mini European 3.5% Fuel Oil Barges FOB Rdam (P...,"For contract details, please see <a href=http:...",2018-11-01 22:11:08,2015-02-12,2018-11-01,2019-01-31

In [17]:
df[df['symbol'].str.startswith('JPY')]

,symbol,name,description,refreshed_at,from_date,to_date,expiration_date
76174,JPYF2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-01-18,2016-01-18
76175,JPYF2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2016-01-05,2017-01-16,2017-01-16
76176,JPYF2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2017-01-04,2017-04-21,2017-04-21
76177,JPYG2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-02-15,2016-02-15
76178,JPYG2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-02-14 01:07:51,2016-02-02,2017-02-13,2017-02-13
76179,JPYG2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2017-01-31,2017-04-21,2017-04-21
76180,JPYH2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-03-14,2016-03-14
76181,JPYH2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-03-14 00:28:32,2015-11-17,2017-03-13,2017-03-13
76182,JPYH2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-03-01,2017-04-21,2017-04-21
76183,JPYH2019,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2017-02-28,2017-04-21,2017-04-21
76184,JPYJ2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-04-18,2016-04-18
76185,JPYJ2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-18 00:21:55,2016-04-05,2017-04-17,2017-04-17
76186,JPYJ2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2017-04-04,2017-04-21,2017-04-21
76187,JPYK2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-05-16,2016-05-16
76188,JPYK2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-05-16 00:12:33,2016-05-03,2017-05-15,2017-05-15
76189,JPYM2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-06-13,2016-06-13
76190,JPYM2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-06-20 00:13:00,2015-11-17,2017-06-19,2017-06-19
76191,JPYM2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-06-01,2017-04-21,2017-04-21
76192,JPYN2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-07-18,2016-07-18
76193,JPYN2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-07-06,2017-04-21,2017-04-21
76194,JPYQ2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-08-15,2016-08-15
76195,JPYQ2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-08-02,2017-04-21,2017-04-21
76196,JPYU2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-09-19,2016-09-19
76197,JPYU2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2015-11-17,2017-04-21,2017-04-21
76198,JPYU2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-09-07,2017-04-21,2017-04-21
76199,JPYV2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-10-17,2016-10-17
76200,JPYV2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-10-04,2017-04-21,2017-04-21
76201,JPYX2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-11-14,2016-11-14
76202,JPYX2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-11-01,2017-04-21,2017-04-21
76203,JPYZ2015,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2015-12-14,2015-12-14
76204,JPYZ2016,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2018-06-29 17:34:10,2015-11-17,2016-12-19,2016-12-19
76205,JPYZ2017,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2015-12-01,2017-04-21,2017-04-21
76206,JPYZ2018,U.S. Dollar / Japanese Yen (USD/JPY) Physicall...,"For contract details, please see <a href=http:...",2017-04-22 00:10:08,2016-12-06,2017-04-21,2017-04-21

In [95]:
df['symbol'].str.replace('^JY', 'JJ')

0              0DF2015
1              0DF2016
2              0DF2017
3              0DF2018
4              0DF2019
5              0DF2020
6              0DF2021
7              0DG2014
8              0DG2015
9              0DG2016
10             0DG2017
11             0DG2018
12             0DG2019
13             0DG2020
14             0DG2021
15             0DH2014
16             0DH2015
17             0DH2016
18             0DH2017
19             0DH2018
20             0DH2019
21             0DH2020
22             0DH2021
23             0DJ2014
24             0DJ2015
25             0DJ2016
26             0DJ2017
27             0DJ2018
28             0DJ2019
29             0DJ2020
              ...
164746    ZRG2017C4_25
164747    ZRG2017C5_25
164748    ZRG2018C3_75
164749     ZRG2018C3_9
164750       ZRG2018C4
164751    ZRG2018C4_25
164752     ZRG2018C4_5
164753     ZRZ2016C3_5
164754    ZRZ2016C3_75
164755     ZRZ2016C3_9
164756       ZRZ2016C4
164757    ZRZ2016C4_25
164758    ZRZ2016C5_25
164759    ZRZ2017C3_75
164760     ZRZ2017C3_9
164761       ZRZ2017C4
164762    ZRZ2017C4_25
164763     ZRZ2017C4_5
164764          ZU2014
164765          ZU2015
164766          ZU2016
164767          ZU2017
164768          ZU2018
164769          ZU2019
164770          ZZ2014
164771          ZZ2015
164772          ZZ2016
164773          ZZ2017
164774          ZZ2018
164775          ZZ2019
Name: symbol, dtype: object

In [80]:
df[df['symbol'].str.startswith('JY')]

Empty DataFrame
Columns: [symbol, name, description, refreshed_at, from_date, to_date, expiration_date]
Index: []

In [81]:
df.iloc[76304]

symbol                                                      JPYF2018
name                    Japanese Yen Futures, January 2018 (JYF2018)
description        For contract details, please see <a href=http:...
refreshed_at                                     2018-01-13 01:05:04
from_date                                        2017-08-15 00:00:00
to_date                                          2018-01-12 00:00:00
expiration_date                                  2018-01-12 00:00:00
Name: 76304, dtype: object